name: gridfieldpreview
---
Injector:
  CacheCacheBackend:
    class: CacheCache\Backends\File
    constructor:
      0:
        dir: ../silverstripe-cache/gridfieldpreview
        file_extension: .cache
  CacheCache:
    class: CacheCache\Cache
    constructor:
      0: %$CacheCacheBackend
      1: 'gridfieldpreview'

  SnappyImageService:
    class: Knp\Snappy\Image
    constructor:
      0: '/usr/local/bin/wkhtmltoimage'
  WkHtmlStringInputService:
    class: Heyday\SilverStripe\WkHtml\Input\String
    constructor:
      0: 'Failed'
  WkHtmlStringOutputService:
    class: Heyday\SilverStripe\WkHtml\Output\String
  WkHtmlGeneratorService:
    class: Heyday\SilverStripe\WkHtml\Generator
    constructor:
      0: %$SnappyImageService
      1: %$WkHtmlStringInputService
      2: %$WkHtmlStringOutputService
      3: %$CacheCache
  GridFieldDataObjectPreview:
    class: GridFieldDataObjectPreview
    constructor:
      0: %$WkHtmlGeneratorService